[profile.default]
src = 'contracts'
out = 'artifacts'
artifacts = 'artifacts'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'


remappings = [
    'forge-std/=lib/forge-std/src/',
    '@inco/lightning/=node_modules/@inco/lightning',
    '@inco/shared/=node_modules/@inco/shared/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/'
]